version: '2'
services:
  proxy:
    extends:
      file: ./proxy/docker-compose.yml
      service: nginx-proxy
  webserver:
    extends:
      file: ./nginx/docker-compose.yml
      service: nginx
    environment:
      - VIRTUAL_HOST=experiments.nmrony.docker,nmrony.docker,itc-blog.nmrony.docker
  php:
    extends:
      file: ./nginx/docker-compose.yml
      service: php
  pma:
    extends:
      file: ./pma/docker-compose.yml
      service: pma
    ports:
      - 8080:80
    environment:
      - VIRTUAL_HOST=pma.nmrony.docker
      - PMA_HOSTS=mysql-dev,test_mariadb
  mysql-dev:
    extends:
      file: ./mariadb/docker-compose.yml
      service: mariadb
    volumes:
      - ${DEV_ZONE}/storage/mysql-common:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nmrony
  nmrony_blog:
    depends_on:
      - mysql-dev
      - pma
    extends:
      file: ./blog/docker-compose.dev.yml
      service: nmrony_blog
    volumes:
      - ${DEV_ZONE}/projects/open-source/nmrony.info:/var/lib/ghost
    environment:
      - VIRTUAL_HOST=blog.nmrony.docker
      - DEV_DOMAIN=http://blog.nmrony.docker
