version: '2'
services:
  nginx:
    image: evild/alpine-nginx:1.9.15-libressl
    container_name: lemp_nginx
    restart: always
    networks:
      - ronsvpn_proxy
    volumes:
      - ./nginx/html:/var/www/html/:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - 80:80
      - 443:443

  php:
    image: yavin/alpine-php-fpm
    container_name: lemp_php
    restart: always
    networks:
      - ronsvpn_proxy
      - ronsvpn_backend
    volumes:
      - ./nginx/html:/var/www/html
    depends_on:
      - mariadb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lemp_pma
    restart: always
    networks:
      - ronsvpn_proxy
      - ronsvpn_backend
    depends_on:
      - mariadb
    environment:
      - PMA_HOST=lemp_mariadb
    ports:
      - 8080:80

  mariadb:
    image: mariadb:latest
    container_name: lemp_mariadb
    restart: always
    networks:
      - ronsvpn_backend
      - ronsvpn_proxy
    volumes:
      - /media/devzone/www/storage/mysql/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nmrony

volumes:
  mariadb-data:
    driver: local

networks:
  ronsvpn_backend:
    external: true
  ronsvpn_proxy:
    external: true
